# Generated by Django 3.1.5 on 2021-07-20 19:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_name", models.CharField(max_length=200)),
                (
                    "label_users_see",
                    models.CharField(default="", max_length=200, null=True),
                ),
            ],
        ),
    ]
