version: "3.4"

services:
  redis:
    image: redis:latest
    hostname: redis
    networks:
      - main
    ports:
      - "6379:6379"
    restart: always

  app:
    image: cornellappdev/pear-django:${IMAGE_TAG}
    hostname: app
    env_file: .env
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn pear.wsgi -b 0.0.0.0:8000"
    depends_on:
      - redis
    networks:
      - main
    restart: on-failure
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - 8000:8000

  celery_worker:
    image: cornellappdev/pear-django:${IMAGE_TAG}
    hostname: celery_worker
    env_file: .env
    command: sh -c "./wait-for-it.sh redis:6379 && ./wait-for-it.sh app:8000 -- celery -A pear worker -l info"
    depends_on:
      - app
      - redis
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - main
    restart: always

  celery_beat:
    image: cornellappdev/pear-django:${IMAGE_TAG}
    hostname: celery_beat
    env_file: .env
    command: sh -c "./wait-for-it.sh redis:6379 && ./wait-for-it.sh app:8000 -- celery -A pear beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - app
      - redis
      - celery_worker
    networks:
      - main
    restart: always

networks:
  main:
