# Generated by Django 3.1.5 on 2021-04-22 08:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("interest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interest",
            name="img_url",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="interest",
            name="subtitle",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
