# Generated by Django 3.1.5 on 2021-04-22 02:48

from django.db import migrations
from django.db import models
import match.validators


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="proposed_meeting_times",
            field=models.TextField(
                default="[]",
                null=True,
                validators=[match.validators.validate_times_list],
            ),
        ),
    ]
