# Generated by Django 3.1.5 on 2021-04-22 03:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0002_auto_20210422_0248"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="created_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
