# Generated by Django 3.1.5 on 2021-04-14 20:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0001_initial"),
        ("match", "0002_auto_20210414_2051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="user_1_groups",
            field=models.ManyToManyField(
                default=None, related_name="_match_user_1_groups_+", to="group.Group"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="user_2_groups",
            field=models.ManyToManyField(
                default=None, related_name="_match_user_2_groups_+", to="group.Group"
            ),
        ),
    ]
