# Generated by Django 3.1.5 on 2021-04-22 03:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0003_match_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
