# Generated by Django 3.1.5 on 2021-04-21 18:08

import re

from django.conf import settings
import django.core.validators
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("match", "0003_auto_20210414_2051"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="user_1_groups",
        ),
        migrations.RemoveField(
            model_name="match",
            name="user_2_groups",
        ),
        migrations.AddField(
            model_name="match",
            name="accepted_ids",
            field=models.CharField(
                default=None,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="user_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="user_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
