# Generated by Django 3.1.5 on 2021-05-08 18:24

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("match", "0004_auto_20210422_0350"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="meeting_location",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_confirmed",
                to="location.location",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="proposed_locations",
            field=models.ManyToManyField(
                default=None, related_name="matches_proposed", to="location.Location"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="user_1",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="user_2",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
