# Generated by Django 3.1.5 on 2021-05-10 03:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0005_auto_20210508_1824"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="accepted_ids",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="proposed_meeting_times",
            field=models.TextField(default="[]", null=True),
        ),
    ]
