# Generated by Django 3.1.5 on 2021-06-05 07:03

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("location", "0001_initial"),
        ("group", "0002_auto_20210422_0339"),
        ("interest", "0002_auto_20210422_0819"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("net_id", models.CharField(max_length=10)),
                ("hometown", models.CharField(default=None, max_length=50, null=True)),
                (
                    "profile_pic_url",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                (
                    "facebook_url",
                    models.CharField(default=None, max_length=50, null=True),
                ),
                (
                    "instagram_username",
                    models.CharField(default=None, max_length=30, null=True),
                ),
                (
                    "graduation_year",
                    models.CharField(default=None, max_length=4, null=True),
                ),
                ("pronouns", models.CharField(default=None, max_length=20, null=True)),
                ("goals", models.TextField(default=None, null=True)),
                ("talking_points", models.TextField(default=None, null=True)),
                ("availability", models.TextField(default=None, null=True)),
                ("has_onboarded", models.BooleanField(default=None, null=True)),
                ("groups", models.ManyToManyField(default=None, to="group.Group")),
                (
                    "interests",
                    models.ManyToManyField(default=None, to="interest.Interest"),
                ),
                (
                    "locations",
                    models.ManyToManyField(default=None, to="location.Location"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
