# Generated by Django 3.1.5 on 2021-03-21 02:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0002_person_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="facebook_url",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="person",
            name="graduation_year",
            field=models.CharField(default=None, max_length=4),
        ),
        migrations.AddField(
            model_name="person",
            name="hometown",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="person",
            name="instagram_username",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name="person",
            name="major",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name="person",
            name="profile_pic_url",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="pronouns",
            field=models.CharField(default=None, max_length=20),
        ),
    ]
