# Generated by Django 3.1.5 on 2021-06-08 05:33

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("major", "0001_initial"),
        ("person", "0002_auto_20210605_2135"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="major",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="major.major",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="has_onboarded",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
