# Generated by Django 3.1.5 on 2021-06-09 01:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("major", "0001_initial"),
        ("person", "0003_auto_20210608_0533"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="major",
        ),
        migrations.AddField(
            model_name="person",
            name="major",
            field=models.ManyToManyField(blank=True, default=None, to="major.Major"),
        ),
    ]
