# Generated by Django 3.1.5 on 2021-06-09 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0004_auto_20210609_0144"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="major",
            new_name="majors",
        ),
    ]
