# Generated by Django 3.1.5 on 2021-07-20 19:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("prompt", "0001_initial"),
        ("person", "0006_auto_20210611_1618"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="prompt_answers",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="prompt_questions",
            field=models.ManyToManyField(blank=True, default=None, to="prompt.Prompt"),
        ),
    ]
