# Generated by Django 3.1.5 on 2021-09-29 06:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("purpose", "0001_initial"),
        ("person", "0008_auto_20210919_2006"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="purposes",
            field=models.ManyToManyField(
                blank=True, default=None, to="purpose.Purpose"
            ),
        ),
    ]
