# Generated by Django 3.1.5 on 2021-03-21 04:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0008_auto_20210321_0231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="facebook_url",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
