# Generated by Django 3.1.5 on 2021-03-21 20:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0010_auto_20210321_0522"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
