# Generated by Django 3.1.5 on 2021-10-27 14:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0010_auto_20211021_1754"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="soft_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
