# Generated by Django 3.1.5 on 2021-11-12 06:27

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("push_notifications", "0007_uniquesetting"),
        ("person", "0011_person_soft_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="fcm_device",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="push_notifications.gcmdevice",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="fcm_registration_token",
            field=models.TextField(default=None, null=True),
        ),
    ]
