# Generated by Django 3.1.5 on 2021-03-22 18:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0012_auto_20210322_1840"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="graduation_year",
            field=models.CharField(default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="hometown",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="instagram_username",
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="major",
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="profile_pic_url",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="pronouns",
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
