# Generated by Django 3.1.5 on 2022-03-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_remove_person_fcm_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='pause_expiration',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
