# Generated by Django 3.1.5 on 2021-12-04 03:38

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0013_remove_person_fcm_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="matching_paused",
            field=models.BooleanField(default=False),
        ),
    ]
