# Generated by Django 3.1.5 on 2021-03-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0013_auto_20210322_1840"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="major",
        ),
    ]
