# Generated by Django 3.1.5 on 2022-03-15 18:43

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("person", "0013_remove_person_fcm_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="blocked_users",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="blocked_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
