# Generated by Django 3.1.5 on 2022-03-16 22:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0014_auto_20220302_2328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="is_paused",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="soft_deleted",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
