# Generated by Django 3.1.5 on 2021-04-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0014_remove_person_major"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="id_token",
        ),
    ]
