# Generated by Django 3.1.5 on 2021-04-21 18:08

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("interest", "0001_initial"),
        ("location", "0001_initial"),
        ("match", "0004_auto_20210421_1808"),
        ("group", "0001_initial"),
        ("person", "0015_remove_person_id_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="availability",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="goals",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="groups",
            field=models.ManyToManyField(default=None, to="group.Group"),
        ),
        migrations.AddField(
            model_name="person",
            name="interests",
            field=models.ManyToManyField(default=None, to="interest.Interest"),
        ),
        migrations.AddField(
            model_name="person",
            name="locations",
            field=models.ManyToManyField(default=None, to="location.Location"),
        ),
        migrations.AddField(
            model_name="person",
            name="matches",
            field=models.ManyToManyField(default=None, to="match.Match"),
        ),
        migrations.AddField(
            model_name="person",
            name="onboarded",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="talking_points",
            field=models.TextField(default=None, null=True),
        ),
    ]
