# Generated by Django 3.1.5 on 2022-03-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0015_auto_20220316_2236"),
        ("person", "0014_person_blocked_users"),
    ]

    operations = []
