# Generated by Django 3.1.5 on 2021-05-08 18:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0015_auto_20210508_1830"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="has_onboarded",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
