# Generated by Django 3.1.5 on 2022-03-25 02:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0016_merge_20220321_1402"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="last_active",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
