# Generated by Django 3.1.5 on 2021-07-20 07:38

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("match", "0006_auto_20210510_0302"),
        ("person", "0006_auto_20210611_1618"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("explanation", models.TextField(default=None)),
                ("rating", models.IntegerField(default=None, null=True)),
                (
                    "completed_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="match.match"
                    ),
                ),
                (
                    "submitting_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="person.person",
                    ),
                ),
            ],
        ),
    ]
