# Generated by Django 3.1.5 on 2021-08-08 21:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="did_meet",
            field=models.BooleanField(default=None),
        ),
    ]
