# Generated by Django 3.1.5 on 2022-02-19 21:08

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_survey_did_meet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survey",
            name="explanation",
        ),
        migrations.AddField(
            model_name="survey",
            name="did_meet_reason",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="did_not_meet_reasons",
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="survey",
            name="did_meet",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
