# Generated by Django 3.1.5 on 2022-02-19 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_auto_20220219_2108"),
    ]

    operations = [
        migrations.RenameField(
            model_name="survey",
            old_name="submitting_user",
            new_name="submitting_person",
        ),
    ]
